// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS02g3Gtbz_v_cw9KxOffknGQGsvZKK_s',
    appId: '1:657614790732:web:b5619b35e6dc0dbb7614e9',
    messagingSenderId: '657614790732',
    projectId: 'helpify-flutter',
    authDomain: 'helpify-flutter.firebaseapp.com',
    storageBucket: 'helpify-flutter.firebasestorage.app',
    measurementId: 'G-N175SNWT7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZMCBdviYVlMzj9liXv0oJQolMiV4YkMc',
    appId: '1:657614790732:android:0531d3b6bfb965027614e9',
    messagingSenderId: '657614790732',
    projectId: 'helpify-flutter',
    storageBucket: 'helpify-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB5NxV6PutpXg0O3xN08LkPiIsxyDkUT8',
    appId: '1:657614790732:ios:3d78862e4dbc5db77614e9',
    messagingSenderId: '657614790732',
    projectId: 'helpify-flutter',
    storageBucket: 'helpify-flutter.firebasestorage.app',
    iosBundleId: 'com.example.newHelpify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB5NxV6PutpXg0O3xN08LkPiIsxyDkUT8',
    appId: '1:657614790732:ios:3d78862e4dbc5db77614e9',
    messagingSenderId: '657614790732',
    projectId: 'helpify-flutter',
    storageBucket: 'helpify-flutter.firebasestorage.app',
    iosBundleId: 'com.example.newHelpify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS02g3Gtbz_v_cw9KxOffknGQGsvZKK_s',
    appId: '1:657614790732:web:166e616ec4517fbe7614e9',
    messagingSenderId: '657614790732',
    projectId: 'helpify-flutter',
    authDomain: 'helpify-flutter.firebaseapp.com',
    storageBucket: 'helpify-flutter.firebasestorage.app',
    measurementId: 'G-1QS6WE5HES',
  );
}
